buildscript {
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath "com.android.tools.build:gradle:8.2.1"
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:1.9.24"
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

// Tambahan supaya semua plugin ikut pakai compileSdk & targetSdk 34
subprojects {
    afterEvaluate { project ->
        if (project.hasProperty("android")) {
            project.android {
                if (namespace == null && project.name != "app") {
                    namespace "com.example.bentara.${project.name}"
                }
                compileSdk = 34
                defaultConfig {
                    targetSdk = 34
                }
            }
        }
    }
}
